[package]
name = "libnes"
version = "0.1.0"
authors = ["Eric"]
edition = "2018"
build = "build.rs"

[dependencies]
byteorder = "1.3.1"
bitflags = "1.0.4"
itertools = "0.8.0"

[build-dependencies]
reqwest = "0.9.9"